import { Song } from "../_types/generals.models";



export const sampleList: Array<Song> = [
  { id: 1, fileName: 'song1.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Song One', artist: 'Artist A', album: 'Album X', urlAlbumArt: '' } },
  { id: 2, fileName: 'dancing-in-the-moonlight.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Dancing in the Moonlight', artist: 'King Harvest', album: 'Dancing in the Moonlight', urlAlbumArt: '' } },
  { id: 3, fileName: 'summer-breeze.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 4, fileName: 'electric-dreams.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Electric Dreams', artist: 'Philip Oakey', album: 'Electric Dreams', urlAlbumArt: '' } },
  { id: 5, fileName: 'midnight-city.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 6, fileName: 'sweet-child-of-mine.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Sweet Child O Mine', artist: 'Guns N Roses', album: 'Appetite for Destruction', urlAlbumArt: '' } },
  { id: 7, fileName: 'heart-of-glass.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 8, fileName: 'wonderwall.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Wonderwall', artist: 'Oasis', album: "What's the Story Morning Glory", urlAlbumArt: '' } },
  { id: 9, fileName: 'bohemian-rhapsody.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 10, fileName: 'stairway-to-heaven.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Stairway to Heaven', artist: 'Led Zeppelin', album: 'Led Zeppelin IV', urlAlbumArt: '' } },
  { id: 11, fileName: 'purple-rain.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 12, fileName: 'imagine.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Imagine', artist: 'John Lennon', album: 'Imagine', urlAlbumArt: '' } },
  { id: 13, fileName: 'hotel-california.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 14, fileName: 'smells-like-teen-spirit.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Smells Like Teen Spirit', artist: 'Nirvana', album: 'Nevermind', urlAlbumArt: '' } },
  { id: 15, fileName: 'billie-jean.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 16, fileName: 'like-a-rolling-stone.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Like a Rolling Stone', artist: 'Bob Dylan', album: 'Highway 61 Revisited', urlAlbumArt: '' } },
  { id: 17, fileName: 'sweet-dreams.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 18, fileName: 'dont-stop-believin.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: "Don't Stop Believin'", artist: 'Journey', album: 'Escape', urlAlbumArt: '' } },
  { id: 19, fileName: 'livin-on-a-prayer.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 20, fileName: 'take-on-me.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Take On Me', artist: 'a-ha', album: 'Hunting High and Low', urlAlbumArt: '' } },
  { id: 21, fileName: 'every-breath-you-take.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 22, fileName: 'with-or-without-you.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'With or Without You', artist: 'U2', album: 'The Joshua Tree', urlAlbumArt: '' } },
  { id: 23, fileName: 'africa.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 24, fileName: 'dont-you-forget-about-me.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: "Don't You Forget About Me", artist: 'Simple Minds', album: 'Once Upon a Time', urlAlbumArt: '' } },
  { id: 25, fileName: 'eye-of-the-tiger.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 26, fileName: 'girls-just-want-to-have-fun.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Girls Just Want to Have Fun', artist: 'Cyndi Lauper', album: "She's So Unusual", urlAlbumArt: '' } },
  { id: 27, fileName: 'the-sound-of-silence.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 28, fileName: 'beat-it.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Beat It', artist: 'Michael Jackson', album: 'Thriller', urlAlbumArt: '' } },
  { id: 29, fileName: 'walk-this-way.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 30, fileName: 'paint-it-black.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Paint It Black', artist: 'The Rolling Stones', album: 'Aftermath', urlAlbumArt: '' } },
  { id: 31, fileName: 'under-pressure.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 32, fileName: 'comfortably-numb.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Comfortably Numb', artist: 'Pink Floyd', album: 'The Wall', urlAlbumArt: '' } },
  { id: 33, fileName: 'jump.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 34, fileName: 'lets-dance.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: "Let's Dance", artist: 'David Bowie', album: "Let's Dance", urlAlbumArt: '' } },
  { id: 35, fileName: 'superstition.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 36, fileName: 'born-to-run.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Born to Run', artist: 'Bruce Springsteen', album: 'Born to Run', urlAlbumArt: '' } },
  { id: 37, fileName: 'come-together.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 38, fileName: 'walk-of-life.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Walk of Life', artist: 'Dire Straits', album: 'Brothers in Arms', urlAlbumArt: '' } },
  { id: 39, fileName: 'respect.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 40, fileName: 'i-will-survive.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'I Will Survive', artist: 'Gloria Gaynor', album: 'Love Tracks', urlAlbumArt: '' } },
  { id: 41, fileName: 'fortunate-son.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 42, fileName: 'september.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'September', artist: 'Earth Wind & Fire', album: 'The Best of Earth Wind & Fire Vol. 1', urlAlbumArt: '' } },
  { id: 43, fileName: 'free-bird.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 44, fileName: 'i-want-to-break-free.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'I Want to Break Free', artist: 'Queen', album: 'The Works', urlAlbumArt: '' } },
  { id: 45, fileName: 'my-heart-will-go-on.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 46, fileName: 'rocky-mountain-high.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Rocky Mountain High', artist: 'John Denver', album: 'Rocky Mountain High', urlAlbumArt: '' } },
  { id: 47, fileName: 'man-in-the-mirror.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 48, fileName: 'smooth-criminal.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Smooth Criminal', artist: 'Michael Jackson', album: 'Bad', urlAlbumArt: '' } },
  { id: 49, fileName: 'baba-o-riley.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 50, fileName: 'wish-you-were-here.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Wish You Were Here', artist: 'Pink Floyd', album: 'Wish You Were Here', urlAlbumArt: '' } },
  { id: 51, fileName: 'welcome-to-the-jungle.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 52, fileName: 'i-wanna-dance-with-somebody.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'I Wanna Dance with Somebody', artist: 'Whitney Houston', album: 'Whitney', urlAlbumArt: '' } },
  { id: 53, fileName: 'another-one-bites-the-dust.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 54, fileName: 'somebody-to-love.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Somebody to Love', artist: 'Queen', album: 'A Day at the Races', urlAlbumArt: '' } },
  { id: 55, fileName: 'dancing-queen.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 56, fileName: 'heroes.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Heroes', artist: 'David Bowie', album: 'Heroes', urlAlbumArt: '' } },
  { id: 57, fileName: 'thunder-road.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 58, fileName: 'crazy-little-thing-called-love.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Crazy Little Thing Called Love', artist: 'Queen', album: 'The Game', urlAlbumArt: '' } },
  { id: 59, fileName: 'american-girl.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 60, fileName: 'dream-on.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Dream On', artist: 'Aerosmith', album: 'Aerosmith', urlAlbumArt: '' } },
  { id: 61, fileName: 'mr-blue-sky.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 62, fileName: 'layla.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Layla', artist: 'Derek and the Dominos', album: 'Layla and Other Assorted Love Songs', urlAlbumArt: '' } },
  { id: 63, fileName: 'sweet-emotion.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 64, fileName: 'roxanne.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Roxanne', artist: 'The Police', album: 'Outlandos d\'Amour', urlAlbumArt: '' } },
  { id: 65, fileName: 'money-for-nothing.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 66, fileName: 'living-on-a-prayer.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Living On a Prayer', artist: 'Bon Jovi', album: 'Slippery When Wet', urlAlbumArt: '' } },
  { id: 67, fileName: 'faithfully.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 68, fileName: 'barracuda.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Barracuda', artist: 'Heart', album: 'Little Queen', urlAlbumArt: '' } },
  { id: 69, fileName: 'burning-down-the-house.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 70, fileName: 'take-me-home-tonight.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Take Me Home Tonight', artist: 'Eddie Money', album: "Can't Hold Back", urlAlbumArt: '' } },
  { id: 71, fileName: 'black-velvet.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 72, fileName: 'night-moves.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Night Moves', artist: 'Bob Seger', album: 'Night Moves', urlAlbumArt: '' } },
  { id: 73, fileName: 'summer-of-69.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 74, fileName: 'shout.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Shout', artist: 'Tears for Fears', album: 'Songs from the Big Chair', urlAlbumArt: '' } },
  { id: 75, fileName: 'call-me.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 76, fileName: 'jessies-girl.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: "Jessie's Girl", artist: 'Rick Springfield', album: 'Working Class Dog', urlAlbumArt: '' } },
  { id: 77, fileName: 'time-after-time.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 78, fileName: 'careless-whisper.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Careless Whisper', artist: 'George Michael', album: 'Make It Big', urlAlbumArt: '' } },
  { id: 79, fileName: 'dont-bring-me-down.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 80, fileName: 'you-shook-me-all-night-long.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'You Shook Me All Night Long', artist: 'AC/DC', album: 'Back in Black', urlAlbumArt: '' } },
  { id: 81, fileName: 'hungry-heart.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 82, fileName: 'total-eclipse-of-the-heart.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Total Eclipse of the Heart', artist: 'Bonnie Tyler', album: 'Faster Than the Speed of Night', urlAlbumArt: '' } },
  { id: 83, fileName: 'sunglasses-at-night.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 84, fileName: 'aint-no-sunshine.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: "Ain't No Sunshine", artist: 'Bill Withers', album: 'Just As I Am', urlAlbumArt: '' } },
  { id: 85, fileName: 'rosanna.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 86, fileName: 'karma-chameleon.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Karma Chameleon', artist: 'Culture Club', album: 'Colour by Numbers', urlAlbumArt: '' } },
  { id: 87, fileName: 'wild-horses.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 88, fileName: 'open-arms.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Open Arms', artist: 'Journey', album: 'Escape', urlAlbumArt: '' } },
  { id: 89, fileName: 'separate-ways.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 90, fileName: 'the-chain.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'The Chain', artist: 'Fleetwood Mac', album: 'Rumours', urlAlbumArt: '' } },
  { id: 91, fileName: 'run-to-you.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 92, fileName: 'peace-of-mind.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Peace of Mind', artist: 'Boston', album: 'Boston', urlAlbumArt: '' } },
  { id: 93, fileName: 'more-than-a-feeling.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 94, fileName: 'hold-the-line.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Hold the Line', artist: 'Toto', album: 'Toto', urlAlbumArt: '' } },
  { id: 95, fileName: 'dont-you-worry-child.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 96, fileName: 'bad-moon-rising.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Bad Moon Rising', artist: 'Creedence Clearwater Revival', album: 'Green River', urlAlbumArt: '' } },
  { id: 97, fileName: 'fortunate-one.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 98, fileName: 'sweet-home-alabama.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Sweet Home Alabama', artist: 'Lynyrd Skynyrd', album: 'Second Helping', urlAlbumArt: '' } },
  { id: 99, fileName: 'all-along-the-watchtower.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 },
  { id: 100, fileName: 'smoke-on-the-water.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0, metadata: { title: 'Smoke on the Water', artist: 'Deep Purple', album: 'Machine Head', urlAlbumArt: '' } },
  { id: 101, fileName: 'the-final-countdown.mp3', userScore: 0, tsScore: 0, tsTrainLevelLocal: 0, tsTrainLevelGlobal: 0 }
]